---
apiVersion: "v1"
kind: "Template"
metadata:
  name: "everest"
  annotations:
    description: "A well-designed monolithic application by Arun Gupta."
objects:
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "everest"
    name: "everest"
  spec:
    replicas: "1"
    selector:
      app: "everest"
      deploymentconfig: "everest"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "everest"
          deploymentconfig: "everest"
      spec:
        containers:
        - name: "everest"
          image: "docker.io/metmajer/everest"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
          resources: {}
  status: {}
- apiVersion: v1
  kind: "Service"
  metadata:
    labels:
      app: "everest"
    name: "everest"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "everest"
      deploymentconfig: "everest"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "everest"
  spec:
    to:
      kind: "Service"
      name: "everest"
