---
kind: Template
apiVersion: v1
name: Hawkular OpenShift Agent Project Configuration Template
metadata:
  name: my-hosa-config
  labels:
    metrics-infra: agent
objects:
- kind: ConfigMap
  apiVersion: v1
  name: Hawkular OpenShift Agent Project Configuration
  metadata:
    name: my-hosa-config
    labels:
      metrics-infra: agent
  data:
    hawkular-openshift-agent: |
      endpoints:
      - type: jolokia
        protocol: http
        port: 8778
        path: /jolokia/
        collection_interval: 10s
        metrics:
        - name: java.lang:type=Memory
          type: gauge
          id:   VM Heap Memory Used
        - name: java.lang:type=Threading
          type: counter
          id:   VM Thread Count
      - type: prometheus
        protocol: http
        port: 8080
        path: /metrics
        collection_interval: 10s
        metrics:
        - name: hawkular_openshift_agent_metric_data_points_collected_total
        - name: process_cpu_seconds_total
        - name: go_goroutines
        - name: go_memstats_alloc_bytes
        - name: go_memstats_gc_sys_bytes
        - name: go_memstats_heap_alloc_bytes
        - name: go_memstats_heap_idle_bytes
        - name: go_memstats_heap_inuse_bytes
        - name: go_memstats_heap_objects
        - name: go_memstats_heap_released_bytes
        - name: go_memstats_heap_sys_bytes
        - name: go_memstats_last_gc_time_seconds
        - name: go_memstats_next_gc_bytes
        - name: go_memstats_other_sys_bytes
        - name: go_memstats_stack_inuse_bytes
        - name: go_memstats_stack_sys_bytes
        - name: go_memstats_sys_bytes
        - name: process_max_fds
        - name: process_open_fds
        - name: process_resident_memory_bytes
        - name: process_start_time_seconds
        - name: process_virtual_memory_bytes
